import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import MenuNav from "./components/layout/MenuNav"
import "./globals.css"

const dmSans = DM_Sans({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-dm-sans",
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" className={`${dmSans.variable}`}>
			<body className="font-sans antialiased">
				<div className="flex">
					<MenuNav />

					<main className="flex-1 transition-all duration-300">
						<div className="min-h-[calc(100svh-15px)]">{children}</div>
					</main>
				</div>
			</body>
		</html>
	)
}
